mysql:
    dsn: yoomall:yoomall@tcp(127.0.0.1:3306)/yoomall?charset=utf8mb4&parseTime=True&loc=Local
    host: 127.0.0.1
    user: yoomall
    password: yoomall
    dbname: yoomall
    port: 3306
    charset: utf8mb4
    timezone: "+08:00"

postgres:
    dsn: host=127.0.0.1 user=yoomall password=yoomall dbname=yoomall port=5432 sslmode=disable

    
DEBUG: true

storage_path: ./storage

dtk: 
    app_key: xx
    app_secret: xxx
    app_url: https://openapi.dataoke.com/api/

jutuike:
    pub_id: xx
    api_key: xxxx
    jtk_url: http://api.jutuike.com/



vite:
    url: http://127.0.0.1:5173/
    debug: true
    build_dir: ./public 


site:
    title: "Ship It 1 Day"
    description: "ship1d.com is helping your build your business."
    keywords: "YooMall, Online Shopping, YooMall, YooMall, YooMall"
    author: "YooMall"
    favicon: "/images/favicon.ico"
    logo: "/images/logo.png"