// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lazyfury.github.com/yoomall-server/app"
	"lazyfury.github.com/yoomall-server/config"
	"lazyfury.github.com/yoomall-server/core/http"
)

// Injectors from wire.go:

func NewApp() httpserver.HttpServer {
	configConfig := config.NewConfig()
	db := NewDB(configConfig)
	defaultApp := app.NewWireDefaultApp(configConfig, db)
	httpServer := NewHttpServer(defaultApp)
	return httpServer
}
