// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lazyfury.github.com/yoomall-server/jobs"
)

// Injectors from wire.go:

func NewCron() *jobs.JobServer {
	cron := jobs.NewCorn()
	job1 := jobs.NewJob1()
	jobServer := jobs.NewJobServer(cron, job1)
	return jobServer
}
