// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lazyfury.github.com/yoomall-server/app"
	"lazyfury.github.com/yoomall-server/app/handler"
	"lazyfury.github.com/yoomall-server/config"
	"lazyfury.github.com/yoomall-server/core/http"
	"lazyfury.github.com/yoomall-server/modules/post"
)

// Injectors from wire.go:

func NewApp() httpserver.HttpServer {
	viper := config.NewConfig()
	db := NewDB(viper)
	userHandler := handler.NewUserHandler(db, viper)
	dtkHandler := handler.NewDtkHandler(viper)
	defaultApp := app.NewWireDefaultApp(viper, db, userHandler, dtkHandler)
	postDefaultApp := post.NewDefaultApp(viper, db)
	httpServer := NewHttpServer(viper, defaultApp, postDefaultApp)
	return httpServer
}
